//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoGallery
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arac_Tablosu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Arac_Tablosu()
        {
            this.Sozlesme_Tablosu = new HashSet<Sozlesme_Tablosu>();
        }
    
        public int Arac_Id { get; set; }
        public string Plaka { get; set; }
        public int Model_Id { get; set; }
        public int Arac_Durumu_Id { get; set; }
        public Nullable<decimal> Kira_Ucreti { get; set; }
        public Nullable<decimal> Satis_Ucreti { get; set; }
        public int Yil { get; set; }
        public string Yakit { get; set; }
        public int Km { get; set; }
        public string Renk { get; set; }
        public string Resim { get; set; }
        public int Sube_Id { get; set; }
    
        public virtual Arac_Durumu_Tablosu Arac_Durumu_Tablosu { get; set; }
        public virtual Model_Tablosu Model_Tablosu { get; set; }
        public virtual Subeler_Tablosu Subeler_Tablosu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sozlesme_Tablosu> Sozlesme_Tablosu { get; set; }
    }
}
