//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoGallery
{
    using System;
    using System.Collections.Generic;
    
    public partial class Model_Tablosu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Model_Tablosu()
        {
            this.Arac_Tablosu = new HashSet<Arac_Tablosu>();
        }
    
        public int Model_Id { get; set; }
        public int Marka_Id { get; set; }
        public string Model_Adi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Arac_Tablosu> Arac_Tablosu { get; set; }
        public virtual Marka_Tablosu Marka_Tablosu { get; set; }
    }
}
