//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoGallery
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteri_Tablosu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Musteri_Tablosu()
        {
            this.Sozlesme_Tablosu = new HashSet<Sozlesme_Tablosu>();
        }
    
        public int Musteri_Id { get; set; }
        public string Musteri_Tc { get; set; }
        public string Musteri_Adi_Soyadi { get; set; }
        public System.DateTime Musteri_Dogum_Tarihi { get; set; }
        public string Musteri_Telefon { get; set; }
        public string Musteri_Ehliyet_No { get; set; }
        public System.DateTime Musteri_Ehliyet_Tarihi { get; set; }
        public string Musteri_EMail { get; set; }
        public string Musteri_Adres { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sozlesme_Tablosu> Sozlesme_Tablosu { get; set; }
    }
}
