//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoGallery
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel_Tablosu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personel_Tablosu()
        {
            this.Sozlesme_Tablosu = new HashSet<Sozlesme_Tablosu>();
        }
    
        public int Personel_Id { get; set; }
        public string Personel_Tc { get; set; }
        public string Personel_Adi_Soyadi { get; set; }
        public System.DateTime Personel_Dogum_Tarihi { get; set; }
        public string Personel_Telefon { get; set; }
        public string Personel_EMail { get; set; }
        public string Personel_Adres { get; set; }
        public string Personel_Resim { get; set; }
        public int Personel_Turu_Id { get; set; }
        public int Sube_Id { get; set; }
        public string Personel_Sifre { get; set; }
    
        public virtual Personel_Turu_Tablosu Personel_Turu_Tablosu { get; set; }
        public virtual Subeler_Tablosu Subeler_Tablosu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sozlesme_Tablosu> Sozlesme_Tablosu { get; set; }
    }
}
