//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoGallery._8Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoGallery._8Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD CARS.
        /// </summary>
        internal static string AddCarsButtonAddCars {
            get {
                return ResourceManager.GetString("AddCarsButtonAddCars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colour.
        /// </summary>
        internal static string AddCarsLabelColour {
            get {
                return ResourceManager.GetString("AddCarsLabelColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel.
        /// </summary>
        internal static string AddCarsLabelFuel {
            get {
                return ResourceManager.GetString("AddCarsLabelFuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Km.
        /// </summary>
        internal static string AddCarsLabelKm {
            get {
                return ResourceManager.GetString("AddCarsLabelKm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plate.
        /// </summary>
        internal static string AddCarsLabelPlate {
            get {
                return ResourceManager.GetString("AddCarsLabelPlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent Money.
        /// </summary>
        internal static string AddCarsLabelRentMoney {
            get {
                return ResourceManager.GetString("AddCarsLabelRentMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Money.
        /// </summary>
        internal static string AddCarsLabelSalesMoney {
            get {
                return ResourceManager.GetString("AddCarsLabelSalesMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string AddCarsLabelYear {
            get {
                return ResourceManager.GetString("AddCarsLabelYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Cars.
        /// </summary>
        internal static string AddCarstoolStripMenuItem {
            get {
                return ResourceManager.GetString("AddCarstoolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Customers.
        /// </summary>
        internal static string AddCustomersButtonAddCustomers {
            get {
                return ResourceManager.GetString("AddCustomersButtonAddCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string AddCustomersLabelAddress {
            get {
                return ResourceManager.GetString("AddCustomersLabelAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        internal static string AddCustomersLabelDateofBirth {
            get {
                return ResourceManager.GetString("AddCustomersLabelDateofBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drivers License Date.
        /// </summary>
        internal static string AddCustomersLabelDriversLicenseDate {
            get {
                return ResourceManager.GetString("AddCustomersLabelDriversLicenseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driving License Number.
        /// </summary>
        internal static string AddCustomersLabelDrivingLicenseNunmber {
            get {
                return ResourceManager.GetString("AddCustomersLabelDrivingLicenseNunmber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        internal static string AddCustomersLabelEMail {
            get {
                return ResourceManager.GetString("AddCustomersLabelEMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Surname.
        /// </summary>
        internal static string AddCustomersLabelNameSurname {
            get {
                return ResourceManager.GetString("AddCustomersLabelNameSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Number.
        /// </summary>
        internal static string AddCustomersLabelSecurityNumber {
            get {
                return ResourceManager.GetString("AddCustomersLabelSecurityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        internal static string AddCustomersLabelTelephone {
            get {
                return ResourceManager.GetString("AddCustomersLabelTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Customers.
        /// </summary>
        internal static string AddCustomerstoolStripMenuItem {
            get {
                return ResourceManager.GetString("AddCustomerstoolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD EMPLOYEE.
        /// </summary>
        internal static string AddEmployeeButtonAddEmployee {
            get {
                return ResourceManager.GetString("AddEmployeeButtonAddEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string AddEmployeeLabelPassword {
            get {
                return ResourceManager.GetString("AddEmployeeLabelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Employee.
        /// </summary>
        internal static string AddEmployeetoolStripMenuItem {
            get {
                return ResourceManager.GetString("AddEmployeetoolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cars.
        /// </summary>
        internal static string CarsToolStripMenuItem {
            get {
                return ResourceManager.GetString("CarsToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Customer.
        /// </summary>
        internal static string ChooseCustomersButtonListCustomer {
            get {
                return ResourceManager.GetString("ChooseCustomersButtonListCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract.
        /// </summary>
        internal static string ContractToolStripMenuItem {
            get {
                return ResourceManager.GetString("ContractToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        internal static string CustomersToolStripMenuItem {
            get {
                return ResourceManager.GetString("CustomersToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        internal static string EmployeeToolStripMenuItem {
            get {
                return ResourceManager.GetString("EmployeeToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string ExitToolStripMenuItem {
            get {
                return ResourceManager.GetString("ExitToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string LanguageToolStripMenuItem {
            get {
                return ResourceManager.GetString("LanguageToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string LanguagetoolStripMenuItemEnglish {
            get {
                return ResourceManager.GetString("LanguagetoolStripMenuItemEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string LanguagetoolStripMenuItemFrench {
            get {
                return ResourceManager.GetString("LanguagetoolStripMenuItemFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanase.
        /// </summary>
        internal static string LanguagetoolStripMenuItemJapanase {
            get {
                return ResourceManager.GetString("LanguagetoolStripMenuItemJapanase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        internal static string LanguagetoolStripMenuItemSpanish {
            get {
                return ResourceManager.GetString("LanguagetoolStripMenuItemSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkish.
        /// </summary>
        internal static string LanguagetoolStripMenuItemTurkish {
            get {
                return ResourceManager.GetString("LanguagetoolStripMenuItemTurkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIST ALL CARS.
        /// </summary>
        internal static string ListAllCarsButtonListAllCars {
            get {
                return ResourceManager.GetString("ListAllCarsButtonListAllCars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIST ALL EMPLOYEE.
        /// </summary>
        internal static string ListAllEmployeeButtonListAllEmployee {
            get {
                return ResourceManager.GetString("ListAllEmployeeButtonListAllEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIST CARS.
        /// </summary>
        internal static string ListCarsButtonListCars {
            get {
                return ResourceManager.GetString("ListCarsButtonListCars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Cars.
        /// </summary>
        internal static string ListCarstoolStripMenuItem {
            get {
                return ResourceManager.GetString("ListCarstoolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIST EMPLOYEE.
        /// </summary>
        internal static string ListEmployeeButtonListEmployee {
            get {
                return ResourceManager.GetString("ListEmployeeButtonListEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Employee.
        /// </summary>
        internal static string ListEmployeetoolStripMenuItem {
            get {
                return ResourceManager.GetString("ListEmployeetoolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG IN.
        /// </summary>
        internal static string LoginButtonLogin {
            get {
                return ResourceManager.GetString("LoginButtonLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Fields.
        /// </summary>
        internal static string LoginLabelClearFields {
            get {
                return ResourceManager.GetString("LoginLabelClearFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string LoginLabelExit {
            get {
                return ResourceManager.GetString("LoginLabelExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG IN.
        /// </summary>
        internal static string LoginLabelLogin {
            get {
                return ResourceManager.GetString("LoginLabelLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers who rent a car.
        /// </summary>
        internal static string radioButton1 {
            get {
                return ResourceManager.GetString("radioButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch with at least car rental.
        /// </summary>
        internal static string radioButton10 {
            get {
                return ResourceManager.GetString("radioButton10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch with the least number of vehicles.
        /// </summary>
        internal static string radioButton11 {
            get {
                return ResourceManager.GetString("radioButton11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Car rental customers.
        /// </summary>
        internal static string radioButton2 {
            get {
                return ResourceManager.GetString("radioButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers purchasing vehicles.
        /// </summary>
        internal static string radioButton3 {
            get {
                return ResourceManager.GetString("radioButton3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most rented employee.
        /// </summary>
        internal static string radioButton4 {
            get {
                return ResourceManager.GetString("radioButton4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best selling vehicle employee.
        /// </summary>
        internal static string radioButton5 {
            get {
                return ResourceManager.GetString("radioButton5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum car rental employee.
        /// </summary>
        internal static string radioButton6 {
            get {
                return ResourceManager.GetString("radioButton6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Least selling vehicles.
        /// </summary>
        internal static string radioButton7 {
            get {
                return ResourceManager.GetString("radioButton7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch with the most car rentals.
        /// </summary>
        internal static string radioButton8 {
            get {
                return ResourceManager.GetString("radioButton8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch with the most vehicles.
        /// </summary>
        internal static string radioButton9 {
            get {
                return ResourceManager.GetString("radioButton9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Car.
        /// </summary>
        internal static string RentalCarsButtonListCar {
            get {
                return ResourceManager.GetString("RentalCarsButtonListCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        internal static string RentalContactButtonCalculate {
            get {
                return ResourceManager.GetString("RentalContactButtonCalculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        internal static string RentalContactButtonCar {
            get {
                return ResourceManager.GetString("RentalContactButtonCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        internal static string RentalContactButtonCustomer {
            get {
                return ResourceManager.GetString("RentalContactButtonCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Rental Contract.
        /// </summary>
        internal static string RentalContactButtonListRentalContract {
            get {
                return ResourceManager.GetString("RentalContactButtonListRentalContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Rent Car.
        /// </summary>
        internal static string RentalContactButtonListRentCar {
            get {
                return ResourceManager.GetString("RentalContactButtonListRentCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RENTAL CONTRACT.
        /// </summary>
        internal static string RentalContactButtonRentalContact {
            get {
                return ResourceManager.GetString("RentalContactButtonRentalContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Delivered.
        /// </summary>
        internal static string RentalContactButtonVehicleDelivered {
            get {
                return ResourceManager.GetString("RentalContactButtonVehicleDelivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adress.
        /// </summary>
        internal static string RentalContractLabelAdress {
            get {
                return ResourceManager.GetString("RentalContractLabelAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        internal static string RentalContractLabelBrand {
            get {
                return ResourceManager.GetString("RentalContractLabelBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Day.
        /// </summary>
        internal static string RentalContractLabelFirstDay {
            get {
                return ResourceManager.GetString("RentalContractLabelFirstDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Day.
        /// </summary>
        internal static string RentalContractLabelLastDay {
            get {
                return ResourceManager.GetString("RentalContractLabelLastDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        internal static string RentalContractLabelModel {
            get {
                return ResourceManager.GetString("RentalContractLabelModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Surname.
        /// </summary>
        internal static string RentalContractLabelNameSurname {
            get {
                return ResourceManager.GetString("RentalContractLabelNameSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plate.
        /// </summary>
        internal static string RentalContractLabelPlate {
            get {
                return ResourceManager.GetString("RentalContractLabelPlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent Money.
        /// </summary>
        internal static string RentalContractLabelRentMoney {
            get {
                return ResourceManager.GetString("RentalContractLabelRentMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Number.
        /// </summary>
        internal static string RentalContractLabelSecurityNumber {
            get {
                return ResourceManager.GetString("RentalContractLabelSecurityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        internal static string RentalContractLabelTelephone {
            get {
                return ResourceManager.GetString("RentalContractLabelTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Fee.
        /// </summary>
        internal static string RentalContractLabelTotalFee {
            get {
                return ResourceManager.GetString("RentalContractLabelTotalFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental Contract.
        /// </summary>
        internal static string RentalContracttoolStripMenuItem0 {
            get {
                return ResourceManager.GetString("RentalContracttoolStripMenuItem0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REPORT.
        /// </summary>
        internal static string ReportButtonReport {
            get {
                return ResourceManager.GetString("ReportButtonReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string ReportToolStripMenuItem {
            get {
                return ResourceManager.GetString("ReportToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Car.
        /// </summary>
        internal static string SalesCarsButtonListCar {
            get {
                return ResourceManager.GetString("SalesCarsButtonListCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        internal static string SalesContactButtonCar {
            get {
                return ResourceManager.GetString("SalesContactButtonCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        internal static string SalesContactButtonCustomer {
            get {
                return ResourceManager.GetString("SalesContactButtonCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SALES CONTRACT.
        /// </summary>
        internal static string SalesContactButtonRentalContact {
            get {
                return ResourceManager.GetString("SalesContactButtonRentalContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Date.
        /// </summary>
        internal static string SalesContractLabelPurchaseDate {
            get {
                return ResourceManager.GetString("SalesContractLabelPurchaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Money.
        /// </summary>
        internal static string SalesContractLabelSalesMoney {
            get {
                return ResourceManager.GetString("SalesContractLabelSalesMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Contract.
        /// </summary>
        internal static string SalesContracttoolStripMenuItem {
            get {
                return ResourceManager.GetString("SalesContracttoolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Customer.
        /// </summary>
        internal static string SalesCustomersButtonListCustomer {
            get {
                return ResourceManager.GetString("SalesCustomersButtonListCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE CARS.
        /// </summary>
        internal static string UpdateCarsButtonUpdateCars {
            get {
                return ResourceManager.GetString("UpdateCarsButtonUpdateCars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Cars.
        /// </summary>
        internal static string UpdateCarstoolStripMenuItem {
            get {
                return ResourceManager.GetString("UpdateCarstoolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Customers.
        /// </summary>
        internal static string UpdateCustomersButtonUpdateCustomers {
            get {
                return ResourceManager.GetString("UpdateCustomersButtonUpdateCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string UpdateCustomersLabelAddress {
            get {
                return ResourceManager.GetString("UpdateCustomersLabelAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        internal static string UpdateCustomersLabelDateofBirth {
            get {
                return ResourceManager.GetString("UpdateCustomersLabelDateofBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drivers License Date.
        /// </summary>
        internal static string UpdateCustomersLabelDriversLicenseDate {
            get {
                return ResourceManager.GetString("UpdateCustomersLabelDriversLicenseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driving License Number.
        /// </summary>
        internal static string UpdateCustomersLabelDrivingLicenseNunmber {
            get {
                return ResourceManager.GetString("UpdateCustomersLabelDrivingLicenseNunmber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        internal static string UpdateCustomersLabelEMail {
            get {
                return ResourceManager.GetString("UpdateCustomersLabelEMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Surname.
        /// </summary>
        internal static string UpdateCustomersLabelNameSurname {
            get {
                return ResourceManager.GetString("UpdateCustomersLabelNameSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Number.
        /// </summary>
        internal static string UpdateCustomersLabelSecurityNumber {
            get {
                return ResourceManager.GetString("UpdateCustomersLabelSecurityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        internal static string UpdateCustomersLabelTelephone {
            get {
                return ResourceManager.GetString("UpdateCustomersLabelTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Customers.
        /// </summary>
        internal static string UpdateCustomerstoolStripMenuItem {
            get {
                return ResourceManager.GetString("UpdateCustomerstoolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE EMPLOYEE.
        /// </summary>
        internal static string UpdateEmployeeButtonUpdateEmployee {
            get {
                return ResourceManager.GetString("UpdateEmployeeButtonUpdateEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Employee.
        /// </summary>
        internal static string UpdateEmployeetoolStripMenuItem {
            get {
                return ResourceManager.GetString("UpdateEmployeetoolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string UserToolStripMenuItem {
            get {
                return ResourceManager.GetString("UserToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User was not found.
        /// </summary>
        internal static string Wronglogin {
            get {
                return ResourceManager.GetString("Wronglogin", resourceCulture);
            }
        }
    }
}
